version: '3'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    networks:
      - mynetwork

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    networks:
      - mynetwork

networks:
  mynetwork: